#!/bin/zsh

notify-send "kbd-internal-disable"

# https://askubuntu.com/questions/160945/is-there-a-way-to-disable-a-laptops-internal-keyboard
# Use `xinput list` to find the internal keyboard

# TODO: Can't figure out how to use variables in `rg`
# KBD-INTERNAL="AT Translated Set 2 keyboard"

echo "Disabling internal keyboard"
xinput list \
  | rg -o "AT Translated Set 2 keyboard\s*id=([0-9]*)\s" -r '$1' \
  | xargs -I{} xinput float {}
