#!/bin/zsh

sudo mkdir -p /temp
sudo mkdir -p ~/bin
cd /temp

######################################################################################
### Homebrew #########################################################################
### https://docs.brew.sh/Homebrew-on-Linux ###########################################
######################################################################################
### Note: Not sure I need this
# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
# # Add Homebrew to PATH
# eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)


######################################################################################
### FlatPak ##########################################################################
### https://flatpak.org/setup/Pop!_OS/ ###############################################
######################################################################################
sudo apt install flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo


###################################################################
### ZSH  ##########################################################
###################################################################
sudo apt install zsh
chsh -s $(which zsh)
curl -L git.io/antigen > ~/bin/antigen.zsh
echo "YOU NEED TO LOG OUT AND LOG BACK IN"


######################################################################################
### CLI Package Installs #############################################################
######################################################################################
sudo add-apt-repository ppa:daniel-marynicz/filemanager-actions
sudo add-apt-repository ppa:nilarimogard/webupd8

sudo apt install curl
sudo apt install file
sudo apt install git
sudo apt install build-essential
sudo apt install vim
sudo apt install neofetch # Fancy OS terminal output
sudo apt install tig # Git GUI
sudo apt install gparted # Visualize drives/partitions
sudo apt install silversearcher-ag # Better grep
sudo apt install ripgrep # Saner defaults than ag
sudo apt install autojump # Better grep
sudo apt install lua5.3
sudo apt install xclip # copy/pasta clipboard
sudo apt install pop-desktop # for multi-de switching at login
sudo apt install ranger
sudo apt install lightdm # alternative to `gdm3` display manager
sudo apt install kitty # terminal
sudo apt install xcape # remap kbd keys at the os level
sudo apt install gnome-tweak-tool # GUI for messing with system settings
sudo apt install playerctl # control media keys
sudo apt install blueman # bluetooth manager
sudo apt install compton # window transparency and what not
sudo apt install feh # backgrounds for i3
sudo apt install pcmanfm # file explorer
sudo apt install rofi # alfred!
sudo apt install gnome-dictionary
sudo apt install zeal
sudo apt install mpd
sudo apt install sonata # ??
sudo apt install jq # json parse, I think
sudo apt install arandr # monitor management 
sudo apt install libnotify-bin # send notifications
sudo apt install woeusb # ISO bootable drive maker

###################################################################
### Dotfiles / RCM ################################################
### https://github.com/thoughtbot/rcm #############################
### http://thoughtbot.github.io/rcm/rcm.7.html ####################
### lsrc, mkrc, rcdn, rcup
###################################################################
sudo add-apt-repository ppa:martin-frost/thoughtbot-rcm
sudo apt update
sudo apt install rcm
# TODO: git clone my shiz to ~/.dotfiles
lsrc # dry run, scope out what's going to happen
rcup -v


###################################################################
### i3 ############################################################
###################################################################
# Problem: Black screen in i3 for PopOs
#   https://www.reddit.com/r/i3wm/comments/95gri4/black_screen_functional_i3_under_pop_os_with/
sudo apt install libxcb1-dev libxcb-keysyms1-dev libpango1.0-dev libxcb-util0-dev libxcb-icccm4-dev libyajl-dev libstartup-notification0-dev libxcb-randr0-dev libev-dev libxcb-cursor-dev libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev autoconf xutils-dev libtool automake
sudo add-apt-repository -y ppa:kgilmer/speed-ricer
sudo apt install i3-gaps
sudo apt install polybar
sudo apt install i3lock
sudo apt install i3lock-fancy # https://github.com/meskarune/i3lock-fancy

# https://github.com/Raymo111/i3lock-color/releases
cd ~/bin
wget -O i3lock https://github.com/Raymo111/i3lock-color/releases/download/2.12.c.2/i3lock
chmod u+x i3lock 
sudo /usr/bin/i3lock /usr/bin/i3lock-BAK

# https://github.com/pavanjadhaw/betterlockscreen
cd ~/bin
wget -O betterlockscreen https://git.io/fASUJ
chmod u+x betterlockscreen

### albert ########################################################
# https://github.com/albertlauncher/albert
# https://software.opensuse.org/download.html?project=home:manuelschneid3r&package=albert
cd ~/install
wget https://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_19.10/amd64/albert_0.16.1_amd64.deb
sudo apt install ./code_1.44.1-1586789296_amd64.deb


###################################################################
### Random Installs ###############################################
###################################################################

### copyq #########################################################
sudo add-apt-repository ppa:hluk/copyq
sudo apt install copyq

### VSCode ########################################################
# https://code.visualstudio.com/docs/setup/linux
cd ~/install
wget https://go.microsoft.com/fwlink/?LinkID=760868
sudo apt install ./albert_0.16.1_amd64.deb

### Zoom ########################################################
cd ~/install
wget https://zoom.us/client/latest/zoom_amd64.deb
sudo apt install ./zoom_amd64.deb

### Stacer ########################################################
cd ~/install
wget https://github.com/oguzhaninan/Stacer/releases/download/v1.1.0/stacer_1.1.0_amd64.deb
sudo apt install ./stacer_1.1.0_amd64.deb

### Toggl ########################################################
cd ~/install
echo "You need to use the link to download toggl. TODO"
# wget https://toggl.github.io/toggldesktop/download/linux_deb64-stable/
# sudo apt install ./toggldesktop_7.4.528_amd64.deb

### Node / NPM / Yarn  ############################################
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash

### SpaceVim ######################################################
curl -sLf https://spacevim.org/install.sh | bash

###################################################################
### Nativefier ####################################################
###################################################################
# https://github.com/jiahaog/nativefier
# Install nativefier
npm install nativefier -g
mkdir -p ~/Apps
cd ~/Apps
# Todoist
nativefier --name "todoist" "https://todoist.com/app"
sudo ln -s /home/$(whoami)/Apps/todoist-linux-x64/todoist /usr/local/bin/todoist
# Notion
nativefier --name "notion" "https://www.notion.so/"
sudo ln -s /home/$(whoami)/Apps/notion-linux-x64/notion /usr/local/bin/notion


###################################################################
### Lutris ########################################################
###################################################################
sudo apt install lutris
sudo add-apt-repository -y ppa:graphics-drivers/ppa
sudo dpkg --add-architecture i386
sudo apt update
sudo apt install nvidia-driver-430 libnvidia-gl-430 libnvidia-gl-430:i386
sudo apt install libvulkan1 libvulkan1:i386
echo "YOU NEED TO REBOOT"


###################################################################
### GUI Package Installs ##########################################
###################################################################
sudo apt install discord
sudo apt install steam
sudo apt install google-chrome-stable
sudo apt install slack-desktop
sudo apt install spotify-client
# Battle.net
# Hearthtone
# Magic Aren
# VSCode
# Notion
# TODOist


###################################################################
### GUI Snap Install ##########################################
###################################################################
sudo snap install yakyak
sudo snap install todoist-thibaut


#########################################################################
### Special Install: Magic Mouse Driver #################################
### https://github.com/RicardoEPRodrigues/Linux-Magic-Trackpad-2-Driver #
#########################################################################
sudo apt-get install dkms
cd ~/bin
git clone https://github.com/RicardoEPRodrigues/Linux-Magic-Trackpad-2-Driver.git
cd Linux-Magic-Trackpad-2-Driver
chmod u+x install.sh
sudo ./install.sh


##################################################################
### Special Install: Trackpad #################################
##################################################################
# https://github.com/RicardoEPRodrigues/Linux-Magic-Trackpad-2-Driver
# https://github.com/p2rkw/xf86-input-mtrack


##################################################################
### Settings #####################################################
##################################################################
# TODO: Don't know the settings for these
# natural scroll trackpad
# key repeat

# Keyboard stays active when typing. 
# Useful for if you're setting a mech keyboard on top of internal
gsettings set org.gnome.desktop.peripherals.touchpad disable-while-typing false


################################################################
# Fonts
################################################################
# MacOS Fonts
# https://securitronlinux.com/debian-testing/install-mac-osx-fonts-on-linux-easily/