#!/bin/zsh

# https://github.com/alols/xcape#examples
# http://xahlee.info/linux/linux_swap_control_and_alt_xmodmap.html

Hyper="Hyper_L" # mod4, 133
Control="Control_L"

xmodmap -e "keycode 133 = $Hyper"
xmodmap -e "remove mod4 = $Hyper" 
xmodmap -e "add Control = $Hyper"
