#!/bin/zsh

# https://github.com/alols/xcape#examples
spare_modifier="Hyper_L"
xmodmap -e "keycode 133 = $spare_modifier"
xmodmap -e "remove mod4 = $spare_modifier" # hyper_l is mod4 by default
xmodmap -e "add Control = $spare_modifier"
